###############################################################################
#                                   Template                                  #
###############################################################################
apiVersion: v1
kind: Template
labels:
  app: eris
  template: build-eris
  application: Furballs
message: Build Eris
metadata:
  name: build-eris
  annotations:
    description: Build Eris
    openshift.io/display-name: Build Eris
    openshift.io/long-description: Build Eris
    openshift.io/provider-display-name: ADVLab
    openshift.io/support-url: https://github.com/advlab/eris
    tags: advlab
objects:
###############################################################################
#                                Image Stream                                 #
###############################################################################
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: eris
      monitor: 'true'
      application: Furballs
    name: eris
  spec:
    lookupPolicy:
      local: true
################################################################################
#                             Build Configuration                              #
################################################################################
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: eris
      monitor: 'true'
      application: Furballs
    name: eris
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'eris:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: 'https://github.com/advlab/eris.git'
      sourceSecret:
        name: github-perseus
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'php:7.1'
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
################################################################################
#                            Template Parameters                               #
################################################################################
# parameters:
# - name: POD_NAME
#   description: Pod Name
#   displayName: Pod Name
#   required: true