apiVersion: apps/v1
kind: Deployment
metadata:
  name: eris
  labels:
    app: eris
    monitor: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eris
  template:
    metadata:
      labels:
        app: eris
        monitor: 'true'
    spec:
      containers:
      - name: eris
        image: pangealab/eris:latest
        ports:
        - containerPort: 80
        env:
          - name: SELECTOR
            value: pets
          - name: SERVICE
            value: 'http://a850c381a9ec34a70ab644a84dc30b74-8351632.us-east-2.elb.amazonaws.com/api/items'
---
apiVersion: v1
kind: Service
metadata:
  name: eris
  labels:
    app: eris
    monitor: 'true'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: eris
