# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# trigger: 
# - none
# - master

trigger:
  branches:
    include:
    - deploy

variables:

  ### Variables ###
  accountName: 'stage'
  applicationName: 'eris'
  resourceGroupName: '$(applicationName)-rg'
  appServicePlanName: '$(applicationName)-sp'
  prefix: '$(accountName)-$(applicationName)'
  webAppName: '$(prefix)-app'
  location: 'East US'
  skuName: 'B1'
  skuCapacity: 1

pool:
  vmImage: 'ubuntu-latest'

stages:

  ################################################################################
  #                         Initialize Azure Stage                               #
  ################################################################################
  - stage: Init_Env
    jobs:
      - job: Create_Service_Plan
        steps:
        # Use ARM Template to create Azure Service Plan
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 
            subscriptionId: 
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourceGroupName)'
            location: '$(location)'
            templateLocation: 'Linked artifact'
            csmFile: 'azure-arm/eris-sp.json'
            csmParametersFile: 'azure-arm/eris-sp.parameters.json'
            overrideParameters: '-appServicePlanName $(appServicePlanName) -skuName $(skuName) -skuCapacity $(skuCapacity)'
            deploymentMode: 'Incremental'

  ################################################################################
  #                         Create App Service Stage                             #
  ################################################################################  
  - stage: Create_App_Service
    jobs:
      - job: Create_App_Service
        steps:
        # Use ARM Template to create Azure Application Service
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection:  
            subscriptionId: 
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourceGroupName)'
            location: '$(location)'
            templateLocation: 'Linked artifact'
            csmFile: 'azure-arm/eris-app.json'
            csmParametersFile: 'azure-arm/eris-app.parameters.json'
            overrideParameters: '-webAppName $(webAppName) -appServicePlanName $(appServicePlanName)'
            deploymentMode: 'Incremental'

  ################################################################################
  #                            Deploy Artifact Stage                             #
  ################################################################################  
  - stage: Deploy_Artifact
    jobs:
      - job: Download_Package
        steps:
        # Download latest JAR file package from Artifact Feed
        - task: DownloadPackage@1
          inputs:
            packageType: 'upack'
            feed: 
            view: 
            definition: 
            version: '0.0.*'
            downloadPath: '$(System.ArtifactsDirectory)'

        # Deploy JAR file to Azure Application Service
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 
            appType: 'webAppLinux'
            WebAppName: '$(webAppName)'
            packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'
            RuntimeStack: 'PHP|7.2'