# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# trigger: 
# - none
# - master

trigger:
  branches:
    include:
    - deploy

variables:

  ### Variables ###
  accountName: 'stage'
  applicationName: 'eris'
  resourceGroupName: '$(applicationName)-rg'
  appServicePlanName: '$(applicationName)-sp'
  prefix: '$(accountName)-$(applicationName)'
  webAppName: '$(prefix)-app'
  location: 'East US'
  skuName: 'B1'
  skuCapacity: 1

pool:
  vmImage: 'ubuntu-latest'

stages:

  ################################################################################
  #                            Deploy Artifact Stage                             #
  ################################################################################  
  - stage: Deploy_Artifact
    jobs:
      - job: Download_Package
        steps:
        # Download latest JAR file package from Artifact Feed
        - task: DownloadPackage@1
          inputs:
            packageType: 'upack'
            feed: '3440706d-f58a-48bc-8ada-422c0cf81703/2bd1b001-e228-4900-a84b-e5729ab320ae'
            view: 'd7297a1d-59e8-468d-8c80-a9ed3be6fb7f'
            definition: '2e7594a2-26fe-40cd-af59-8886e59bd9ba'
            version: '0.0.*'
            downloadPath: '$(System.ArtifactsDirectory)'

        # Deploy JAR file to Azure Application Service
        - task: AzureRmWebAppDeployment@4